### PR TITLE
Fixed radius functionality

### PR DESCRIPTION
**Pull request by Jurian**
Hi there, for my PhD research I needed to do ANN search in embedding spaces and, your package has helped me out a lot! Thank you :-) 

The only thing missing that I required was fixed radius ANN search, so I wrote some code to do this with your package.

I added:

1. Fixed radius ANN search in the nn.cpp style (one shot build, query and destroy)
2. Fixed radius WANN search (KD-tree re-use)
3. Tests for fixed radius search

If you find the additions acceptable, others could use the extra functionality as well

Cheers,

Jurian Baas

Intelligent Systems Department
Faculty of Science
Utrecht University

### CODE REVIEW

**Comment by jefferis** [comment]
Dear @Jurian, thanks so much for your PR. It's great to hear that this library was useful for your thesis work. 

regarding the details of your PR, I generally try to reuse and avoid duplication wherever possible. I think the duplicated code in at the c++ end (i.e. `queryANN_FR` ) is probably ok but I would def be inclined not to make a new R function but to reuse the existing one. If you take a look at https://github.com/jefferislab/RANN/blob/master/R/nn.R#L65 you'll see that the `radius` is offered as an optional example. In that case the fixed radius search is actually selected in C code not R code.

Would you be able to update your PR with these changes. When it looks good, could you also update the `NEWS.md` and add yourself as a contributor

https://github.com/jefferis/RANN2/blob/05d6eb285ed7b0f6d3b20b9a731fe0398e2954cb/DESCRIPTION#L5

(i.e. `role = "ctb"`)

Thanks and best wishes, Greg.

**Comment by Jurian** [comment]
Hi @jefferis,

Thanks for your comments, the reason I created duplicate code is that I didn't want to edit your existing code.

I have pushed three more commits where I have removed duplicate code and instead integrated the fixed radius search into the existing methods using an optional 'radius' argument.

The only thing that bugs me is that even though I supply the radius argument with a value, it does not seem to recognize it as optional when calling the WANN tree object methods. I think you have had this issue too, as you seem to specify the epsilon argument in the test code instead of leaving it out and letting it default to 0.

I added myself as a contributor and edited the news file as well :-)

The code passes all checks on my end (the 'check' button in Rstudio under the build tab) with 0 errors, 0 warnings and 0 notes, and it seems Travis is happy as well.

Cheers Jurian

**Comment by jefferis** [comment]
For those WANN methods, I actually think it is better to make new methods as you had done — otherwise as you have seen there will be a change in the signature, as the default radius argument cannot be used and must always be provided. For the main C++ nn2 function, the additional default argument is fine.

**Comment by Jurian** [comment]
Hi @jefferis, the WANN methods have been reverted back to their separated form. I left the others as is. Are you fine with it now?

**Pull request merged**
